export const COLORS = [
	'#e74c3c', '#3498db', '#2ecc71', '#f39c12', '#9b59b6',
	'#1abc9c', '#e67e22', '#34495e', '#f1c40f', '#e91e63',
	'#8e44ad', '#27ae60', '#2980b9', '#d35400', '#c0392b',
	'#7f8c8d'
];

export const CONSTANTS = {
	EARTH_RADIUS_M: 6371000,
	EARTH_CIRCUMFERENCE_M: 40075016.686,
	METERS_PER_LAT: 110540,
	METERS_PER_LNG: 111320,
	SPEED_OF_SOUND_MS: 343,

	AUDIO_UPDATE_MS: 50,
	AUTOSAVE_MS: 15000,
	DEBOUNCE_DRAG_MS: 0,
	DRAG_END_COOLDOWN_MS: 0,

	UI_RETRY_DELAY_MS: 100,
	AUDIO_START_DELAY_MS: 100,
	SOUND_LOAD_DELAY_MS: 50,
	AUDIO_UPDATE_AFTER_LOAD_MS: 1000,
	FILE_DELETE_FEEDBACK_MS: 500,

	STATUS_FADE_MS: 300,
	STATUS_SHORT_MS: 1500,
	STATUS_MEDIUM_MS: 2000,
	STATUS_LONG_MS: 3000,

	GEOLOCATION_TIMEOUT_MS: 10000,
	GEOLOCATION_MAX_AGE_MS: 600000,
	WATCH_POSITION_TIMEOUT_MS: 15000,
	WATCH_POSITION_MAX_AGE_MS: 300000,
	GEOLOCATION_FILTER_DEFAULTS: {
		sampleRateHz: 5,
		windowSize: 3,
		sigmaAcc: 1.0,
		maxSpeed: 30,
		minMove: 5,
		holdTime: 1.5
	},
	GPS_SMOOTHING_DEFAULT: 0.5,
	GEOLOCATION_STATUS: {
		INITIAL: 'initial',
		SEARCHING: 'searching',
		ACTIVE: 'active',
		ERROR: 'error',
		DISABLED: 'disabled'
	},

	ORIENTATION_FILTER_DEFAULTS: {
		windowSize: 5,
		sigmaAcc: 2.0,
		maxAngularSpeed: 180,
		minMove: 2,
		holdTime: 0.1
	},
	ORIENTATION_DEFAULT_ACCURACY: 15,

	GPS_INSTABILITY_CONFIG: {
		baselineTimeConstant: 60,
		instabilityTimeConstant: 2.0,
		shapeExponent: 1.3
	},
	GPS_INSTABILITY_REACTIVITY_DEFAULT: 0.5,

	MIDI_MIN: 36,
	MIDI_MAX: 84,

	FILTER_MIN: 100,
	FILTER_MAX: 8000,
	FILTER_RANGE_STEP: 50,

	DETUNE_MIN: -1200,
	DETUNE_MAX: 1200,

	AUDIO_STOP_BUFFER_MS: 20,

	AUDIO_RAMP_TIME: 0.1,
	AUDIO_QUICK_RAMP_TIME: 0.01,
	LFO_SMOOTH_RAMP_TIME: 0.05,
	LFO_HARD_EDGE_RAMP_TIME: 0.001,
	LAYER_SWITCH_RAMP_TIME: 0.02,
	PANNER_RAMP_TIME: 0.05,
	SUSTAIN_RAMP_TIME: 0.05,
	AMBISONIC_GAIN_RAMP_TIME: 0.1,
	ERROR_RECOVERY_RAMP_TIME: 0.05,

	AUDIO_SMOOTHING_ALPHA: 0.15,
	AUDIO_MAX_GAIN_DELTA: 0.05,
	AUDIO_DEAD_ZONE_RADIUS: 8,
	AUDIO_POSITION_WORK_MIN_DISTANCE: 0.05,

	MODULATION_FREQ_MIN: 20,
	MODULATION_FREQ_MAX: 8000,
	CENTS_PER_OCTAVE: 1200,
	DEFAULT_MOD_MAX_DISTANCE: 500,

	DEFAULT_SYNTH_VOLUME_DB: 12,

	PANNER_3D_MODEL: "HRTF",
	PANNER_3D_DISTANCE_MODEL: "linear",
	PANNER_3D_REF_DISTANCE: 1,
	PANNER_3D_MAX_DISTANCE: 10000,
	PANNER_3D_ROLLOFF_FACTOR: 1,
	PANNER_3D_SMOOTHING_TIME: 1,

	AMBISONIC_ORDER: 1,
	AMBISONIC_ROLLOFF: 'linear',
	AMBISONIC_MIN_DISTANCE: 1,
	AMBISONIC_GAIN_BOOST: 1.0,
	AMBISONIC_STEREO_WIDTH: 1.0,
	AMBISONIC_STEREO_SPREAD: 5.0,

	MASTER_VOLUME_DEFAULT_DB: 0,
	MASTER_VOLUME_MIN_DB: -40,
	MASTER_VOLUME_MAX_DB: 12,
	MASTER_VOLUME_RAMP_TIME: 0.02,

	MASTER_METER_FFT_SIZE: 2048,
	MASTER_METER_FLOOR_DB: -60,
	MASTER_METER_FRAME_INTERVAL: 1 / 30,
	MASTER_METER_MAX_FRAME_TIME: 0.25,
	MASTER_METER_PEAK_DECAY_DB_PER_SEC: 24,
	MASTER_METER_RMS_TIME_CONSTANT: 0.3,
	MASTER_METER_HOLD_TIME: 2,
	MASTER_METER_HOLD_DECAY_DB_PER_SEC: 12,
	MASTER_METER_CLIP_THRESHOLD: 0.999,
	MASTER_METER_CLIP_HOLD_TIME: 1.5,
	MASTER_METER_TARGET_LOW_DB: -18,
	MASTER_METER_TARGET_HIGH_DB: -12,
	MASTER_METER_SCALE_TICKS_DB: [-60, -48, -36, -24, -18, -12, -6, 0],
	MASTER_MONITOR_PERSIST_MS: 400,

	ECHO_MAX_AUDIBLE_DISTANCE: 34300,
	ECHO_MAX_DELAY: 100,
	ECHO_LEVEL: 0.2,
	ECHO_INERTIA: 1,
	ECHO_REFLECTIVITY: 0.2,

	DEFAULT_USER_ZOOM: 16,
	DEFAULT_FALLBACK_ZOOM: 2,
	CONTENT_FIT_PADDING: [60, 60],
	REMOTE_BUZZ_DISTANCE_M: 2000,
	MAX_TILE_NATIVE_ZOOM: 18,
	MAX_MAP_ZOOM: 19,
	MENU_DRAG_MIN_VISIBLE: 60,
	MENU_DRAG_IGNORE_SELECTOR: 'button, input, select, textarea, a, label, canvas, .menu-close-btn, .element-nav-dropdown, .collapsible-section-header, .tab-bar, .dual-range-container, .keyboard-container',

	MARKER_CLICK_THRESHOLD: 10,
	POLYGON_VERTEX_CLICK_THRESHOLD_TOUCH: 25,
	POLYGON_EDGE_THRESHOLD: 0.01,
	MIN_RADIUS: 10,
	LONG_PRESS_DELAY: 200,
	DOUBLE_TAP_MS: 300,

	DEFAULT_POLYGON_SIZE: 100,
	DEFAULT_CIRCLE_RADIUS: 100,
	DEFAULT_OVAL_RADIUS_Y: 60,
	DEFAULT_LINE_TOLERANCE: 20,
	LINE_SEMICIRCLE_SEGMENTS: 16,
	SOUND_AREA_FILL_OPACITY: 0.05,
	DEFAULT_OVAL_ASPECT_RATIO: 0.6,
	LINE_PATH_BUFFER_M: 50,
	OVAL_RESOLUTION: 64,

	LFO_MAX_RANGE: 10000,
	LFO_MIN_RANGE: 10,
	LFO_RANGE_STEP: 5,
	DEFAULT_LFO_MAX_RANGE: 500,

	PITCH_MIN: 0,
	PITCH_MAX: 127,

	FREQUENCY_MIN: 20,
	FREQUENCY_MAX: 20000,

	ENVELOPE_TIME_MIN: 0.01,
	ENVELOPE_TIME_MAX: 2,
	ENVELOPE_TIME_STEP: 0.01,
	RELEASE_MAX: 10,
	RELEASE_MIN: 0.1,
	RELEASE_STEP: 0.1,
	RELEASE_CURVE_POINTS: 64,
	RELEASE_CURVE_FLOOR_DB: 60,
	SUSTAIN_MIN: 0,
	SUSTAIN_MAX: 1,

	RESONANCE_MIN: 0.1,
	RESONANCE_MAX: 20,
	RESONANCE_STEP: 0.1,

	HARMONICITY_MIN: 0.1,
	HARMONICITY_MAX: 10,
	HARMONICITY_STEP: 0.1,

	MOD_INDEX_MIN: 0,
	MOD_INDEX_MAX: 100,

	VOLUME_MIN: 0,
	VOLUME_MAX: 1,
	VOLUME_STEP: 0.01,

	PAN_MIN: -1,
	PAN_MAX: 1,
	PAN_STEP: 0.01,

	PULSE_WIDTH_MIN: 0.01,
	PULSE_WIDTH_MAX: 0.99,
	PULSE_WIDTH_STEP: 0.01,

	PORTAMENTO_MIN: 0,
	PORTAMENTO_MAX: 1,
	PORTAMENTO_STEP: 0.01,

	LFO_FREQ_MIN: 0,
	LFO_FREQ_MAX: 2,
	LFO_FREQ_STEP: 0.01,

	MOD_PARAM_MIN: 0,
	MOD_PARAM_MAX: 100,
	MOD_PARAM_STEP: 1,

	REFERENCE_SPEED_MIN: 0.5,
	REFERENCE_SPEED_MAX: 15,
	REFERENCE_SPEED_STEP: 0.1,
	REFERENCE_SPEED_DEFAULT: 1.4,
	ZERO_SPEED_THRESHOLD: 0.01,
	SPEED_IDLE_TIMEOUT: 1.5,
	MIN_PLAYBACK_RATE: 0.1,
	MAX_PLAYBACK_RATE: 4,
	GAIN_RAMP_TIME: 0.1,
	LOOP_FADE_MIN: 0.01,
	LOOP_FADE_SCHEDULE_AHEAD: 2,
	MIN_TRACKING_DISTANCE: 0.001,

	GRANULAR_ADAPTIVE_SPEED_MIN: 0,
	GRANULAR_ADAPTIVE_SPEED_MAX: 8,
	GRANULAR_ADAPTIVE_GRAIN_SIZE_AT_MIN_SPEED: 0.2,
	GRANULAR_ADAPTIVE_GRAIN_SIZE_AT_MAX_SPEED: 0.02,
	GRANULAR_ADAPTIVE_OVERLAP_FACTOR: 0.5,

	MAP_PANE_Z: {
		soundArea: 400,
		controlPathBack: 450,
		controlPathFront: 550,
		soundElement: 600,
		userMarker: 700
	},

	SIM_TARGET_ICON_SIZE: [24, 24],
	SIM_TARGET_ICON_ANCHOR: [4, 24],

	SOUND_ICON_SIZE: [16, 16],
	SOUND_ICON_ANCHOR: [8, 8],
	USER_ICON_SIZE: [20, 20],
	USER_ICON_ANCHOR: [10, 10],
	RADIUS_HANDLE_SIZE: [12, 12],
	RADIUS_HANDLE_ANCHOR: [6, 6],
	VERTEX_HANDLE_SIZE: [8, 8],
	VERTEX_HANDLE_ANCHOR: [4, 4],
	VERTEX_HANDLE_SIZE_TOUCH: [16, 16],
	VERTEX_HANDLE_ANCHOR_TOUCH: [8, 8],

	FILE_SIZE_BASE: 1024,

	TWO_PI: Math.PI * 2,
	SAVE_FORMAT_VERSION: "1.0",

	DEFAULT_SOUND: {
		pitch: 60,
		frequency: 440,
		attack: 0.1,
		decay: 0.2,
		sustain: 0.3,
		release: 0.5,
		filterFreq: 1000,
		filterType: "lowpass",
		resonance: 1,
		curveStrength: 1.0,
		volume: 0.8,
		releaseMode: "stop",
		detune: 0,
		portamento: 0,
		harmonicity: 1,
		pulseWidth: 0.5,
		count: 3,
		spread: 20,
		pan: 0,
		polyphony: 1,
		speedAdvance: false,
		speedAdvanceThreshold: 0.2,
		speedGateMin: 0,
		speedGateMax: 10
	},

	DEFAULT_EQ_VALUES: {
		enabled: false,
		low: 0,
		mid: 0,
		high: 0,
		lowFrequency: 400,
		highFrequency: 2500
	},

	SEQUENCER_MIN_DELTA: 3,
	SEQUENCER_IDLE_SAMPLE_SECONDS: 0.5,
	SEQUENCER_GPS_JUMP_THRESHOLD: 100,
	SEQUENCER_SMOOTH_SAMPLES: 3,
	SEQUENCER_SPEED_WINDOW_MS: 6000,
	AUDIO_LATENCY_HINT: 'playback',
	SEQUENCER_TRACK_POLYPHONY: 8,
	SEQUENCER_DEFAULT_STEPS: 16,
	SEQUENCER_DEFAULT_LENGTH: 10,
	SEQUENCER_MAX_STEPS: 64,
	SEQUENCER_MIN_STEPS: 1,
	SEQUENCER_SPEED_THRESHOLD: 0.5,
	SEQUENCER_SPEED_GATE_MIN: 0,
	SEQUENCER_SPEED_GATE_MAX: 10,
	SEQUENCER_SPEED_GATE_STEP: 0.1,
	SEQUENCER_SPEED_GATE_HOLD_MAX: 10,
	SEQUENCER_SPEED_GATE_HOLD_STEP: 0.1,
	SEQUENCER_SPEED_GATE_HOLD_DEFAULT: 0,
	MODULATION_INERTIA_MIN: 0,
	MODULATION_INERTIA_MAX: 5,
	MODULATION_INERTIA_STEP: 0.05,
	SEQUENCER_SPEED_SCALE_MIN: 1,
	SEQUENCER_SPEED_SCALE_MAX: 20,
	SEQUENCER_SPEED_SCALE_STEP: 0.5,
	SEQUENCER_SYNTH_GAIN: 0.15,
	SEQUENCER_SOUND_FILE_GAIN: 0.5,
	SEQUENCER_VELOCITY_RAMP: 0.02,

	DEFAULT_LAYER_GAIN: 1.0,
	FX_BYPASS_MARGIN_S: 2,
	FX_BYPASS_MAX_TAIL_S: 30,
	FX_BYPASS_RAMP_TIME: 0.02,
	SEQUENCER_BYPASS_FADE: 0.35,
	ALGORITHMIC_REVERB_TAIL_S: 8,
	FX_TAIL_FLOOR: 0.001,
	FX_PROPERTY_WRITE_EPSILON: 0.001,

	SIMULATION_UPDATE_HZ: 5,
	SIMULATION_DEVICE_UPDATE_HZ: 1,
	SIMULATION_SPEED_SCALE_MIN: 0.25,
	SIMULATION_SPEED_SCALE_MAX: 3,
	SIMULATION_SPEED_SCALE_STEP: 0.05,
	SIMULATION_VARIABILITY_MAX: 1,
	SIMULATION_VARIABILITY_STEP: 0.05,
	SIMULATION_VARIABILITY_REVERSION: 0.6,
	SIMULATION_MIN_SPEED_FACTOR: 0.15,
	SIMULATION_NOISE_R68_TO_SIGMA: 1 / 1.509,
	SIMULATION_NOISE_SLOW_TAU_S: 60,
	SIMULATION_NOISE_FAST_TAU_S: 6,
	SIMULATION_NOISE_SLOW_VARIANCE_SHARE: 0.85,
	SIMULATION_NOISE_ACCURACY_FACTOR: 1.2,
	SIMULATION_NOISE_ACCURACY_FLOOR_M: 3,

	ELEMENT_COLORS: COLORS.slice(0, 10),

	TEST_STREAM_URL: 'https://livestreaming-node-4.srg-ssr.ch/srgssr/rsj/mp3/128'
};

CONSTANTS.SIMULATION_UPDATE_INTERVAL_MS = 1000 / CONSTANTS.SIMULATION_UPDATE_HZ;
CONSTANTS.SIMULATION_DEVICE_UPDATE_INTERVAL_MS = 1000 / CONSTANTS.SIMULATION_DEVICE_UPDATE_HZ;

export const PATH_COLORS = COLORS.slice(0, 6);
